package org.ne.gui;

import org.ne.process.CoreProcess;
import org.ne.var.GlobalVar;

/**
 * Edit Window.<br>
 * Design IDE : NetBeans 7.0
 * 
 * @author Ballad
 */
public class EditWindow extends javax.swing.JFrame {

	/** Creates new form EditWindow */
	public EditWindow() {

		initComponents();

		initCust();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel7 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setName("Form"); // NOI18N
		setResizable(false);

		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application
				.getInstance().getContext().getResourceMap(EditWindow.class);
		jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
		jPanel1.setName("jPanel1"); // NOI18N

		jRadioButton1.setBackground(resourceMap
				.getColor("jRadioButton1.background")); // NOI18N
		jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
		jRadioButton1.setName("jRadioButton1"); // NOI18N
		jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);
			}
		});

		jRadioButton2.setBackground(resourceMap
				.getColor("jRadioButton2.background")); // NOI18N
		jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
		jRadioButton2.setName("jRadioButton2"); // NOI18N
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton2ActionPerformed(evt);
			}
		});

		jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
		jLabel2.setName("jLabel2"); // NOI18N

		jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
		jTextField1.setName("jTextField1"); // NOI18N

		jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
		jLabel3.setName("jLabel3"); // NOI18N

		jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
		jTextField2.setName("jTextField2"); // NOI18N

		jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
		jLabel4.setName("jLabel4"); // NOI18N

		jTextField3.setText(resourceMap.getString("jTextField3.text")); // NOI18N
		jTextField3.setName("jTextField3"); // NOI18N

		jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
		jLabel5.setName("jLabel5"); // NOI18N

		jTextField4.setText(resourceMap.getString("jTextField4.text")); // NOI18N
		jTextField4.setName("jTextField4"); // NOI18N

		jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
		jLabel6.setName("jLabel6"); // NOI18N

		jTextField5.setText(resourceMap.getString("jTextField5.text")); // NOI18N
		jTextField5.setName("jTextField5"); // NOI18N

		jSeparator1.setName("jSeparator1"); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jRadioButton1)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jLabel6)
																										.addComponent(
																												jLabel2)
																										.addComponent(
																												jLabel3)
																										.addComponent(
																												jLabel4)
																										.addComponent(
																												jLabel5))
																						.addGap(
																								57,
																								57,
																								57)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												jTextField5)
																										.addComponent(
																												jTextField4)
																										.addComponent(
																												jTextField3)
																										.addComponent(
																												jTextField2)
																										.addComponent(
																												jTextField1,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												134,
																												Short.MAX_VALUE)))
																		.addComponent(
																				jRadioButton2,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				291,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				156,
																				156,
																				156)
																		.addComponent(
																				jSeparator1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				10,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jRadioButton1)
																		.addGap(
																				9,
																				9,
																				9)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jRadioButton2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jTextField5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(19, Short.MAX_VALUE)));

		jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
		jLabel1.setName("jLabel1"); // NOI18N

		jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
		jButton1.setName("jButton1"); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
		jButton2.setName("jButton2"); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jSeparator2.setName("jSeparator2"); // NOI18N

		jSeparator3.setName("jSeparator3"); // NOI18N

		// jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]
		// {
		// "Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox1.setName("jComboBox1"); // NOI18N
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
		jLabel7.setName("jLabel7"); // NOI18N

		jTextField6.setText(resourceMap.getString("jTextField6.text")); // NOI18N
		jTextField6.setName("jTextField6"); // NOI18N
		jTextField6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField6ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				72,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2)
																		.addGap(
																				21,
																				21,
																				21))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel7))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								205,
																								Short.MAX_VALUE)
																						.addComponent(
																								jComboBox1,
																								0,
																								205,
																								Short.MAX_VALUE))
																		.addContainerGap())))
						.addComponent(jPanel1,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jSeparator3,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 327,
								Short.MAX_VALUE).addComponent(jSeparator2,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, 327,
								Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(18, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																jTextField6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addComponent(
												jSeparator3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												2,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												2,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(12, 12, 12)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton1))
										.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * The Plan Name.
	 * 
	 * @param evt
	 */
	private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * Obtain an IP address automatically<br>
	 * 
	 * @param evt
	 */
	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		if (jRadioButton1.isSelected()) {
			jTextField1.setText("");
			jTextField2.setText("");
			jTextField3.setText("");

			jTextField1.setEditable(false);
			jTextField2.setEditable(false);
			jTextField3.setEditable(false);

			isIpAuto = GlobalVar.SET_IP_VALUE_AUTO;
		} else {

			jTextField1.setEditable(true);
			jTextField2.setEditable(true);
			jTextField3.setEditable(true);

			isIpAuto = GlobalVar.SET_IP_VALUE_MANUAL;
		}
	}

	/**
	 * Obtain DNS server address automatically<br>
	 * 
	 * @param evt
	 */
	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {

		if (jRadioButton2.isSelected()) {
			jTextField4.setText("");
			jTextField5.setText("");

			jTextField4.setEditable(false);
			jTextField5.setEditable(false);

			isDnsAuto = GlobalVar.SET_DNS_VALUE_AUTO;
		} else {

			jTextField4.setEditable(true);
			jTextField5.setEditable(true);

			isDnsAuto = GlobalVar.SET_DNS_VALUE_MANUAL;
		}
	}

	/**
	 * OK Button:<br>
	 * 
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		// Check the input values START.
		// The Name of plan is required.
		if (jTextField6.getText().equals("") || jTextField6.getText() == null) {
			// TODO ALERT
			return;

		}

		// If IP Manual: IP ADDR and SUBNET MASK are required.
		if (!jRadioButton1.isSelected()) {

			if (jTextField1.getText().equals("")
					|| jTextField1.getText() == null) {
				// TODO ALERT
				return;

			}
			if (jTextField2.getText().equals("")
					|| jTextField2.getText() == null) {
				// TODO ALERT
				return;

			}
		}

		// If DNS Manual: DNS ADDR 1 is required.
		if (!jRadioButton1.isSelected()) {

			if (jTextField4.getText().equals("")
					|| jTextField4.getText() == null) {
				// TODO ALERT
				return;
			}
		}

		// Check the input values END.

		String[] planCont = { jTextField6.getText(),
				jComboBox1.getSelectedItem().toString(), jTextField1.getText(),
				jTextField2.getText(), jTextField3.getText(),
				jTextField4.getText(), jTextField5.getText(), isIpAuto,
				isDnsAuto };

		if (editFlag == GlobalVar.EDITWINDOW_EDIT_FLAG_CREATE) {
			if (process.create(planCont)) {

			} else {
				// Create Error
				// TODO ALERT 
				return;
			}
		} else {
			// IF Condition: editFlag == EDIT_FLAG_UPDATE
			// We won't handle the update ERROR, because if the source plan for
			// update is null, we will create new plan.
			// @see Map
			process.update(planCont);
		}

		process.saveConfig();

		MainWindowView.refreshJComboBox();

		this.setVisible(false);
	}

	/**
	 * CANCEL Button: Close the Edit Window.
	 * 
	 * @param evt
	 */
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

		this.setVisible(false);
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new EditWindow().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables

	// //////////////////////////////////////////////////////////////////////////////
	// Below are custom objects

	private CoreProcess process;

	/**
	 * @see GlobalVar
	 */
	private String isIpAuto;

	/**
	 * @see GlobalVar
	 */
	private String isDnsAuto;

	// //////////////////////////////////////////////////////////////////////////////
	// Static variables.

	private static final long serialVersionUID = 1L;

	private int editFlag;

	// //////////////////////////////////////////////////////////////////////////////
	// Below are custom methods

	private void initCust() {
		process = CoreProcess.getCoreProcess();

		refreshJComboBox();

		isIpAuto = GlobalVar.SET_IP_VALUE_MANUAL;
		isDnsAuto = GlobalVar.SET_DNS_VALUE_MANUAL;
	}

	/**
	 * Set the default values for TextFields.
	 */
	public void initBeforeShow(String[] args) {

		refreshJComboBox();

		jTextField1.setEditable(true);
		jTextField2.setEditable(true);
		jTextField3.setEditable(true);
		jTextField4.setEditable(true);
		jTextField5.setEditable(true);

		if (editFlag == GlobalVar.EDITWINDOW_EDIT_FLAG_CREATE) {

			jTextField1.setText("");
			jTextField2.setText("");
			jTextField3.setText("");
			jTextField4.setText("");
			jTextField5.setText("");

			// Network Plan Name.
			jTextField6.setText("");

			//jComboBox1.setSelectedIndex(0);

			isIpAuto = GlobalVar.SET_IP_VALUE_MANUAL;
			isDnsAuto = GlobalVar.SET_DNS_VALUE_MANUAL;

			jRadioButton1.setSelected(false);
			jRadioButton2.setSelected(false);

		} else {
			// editFlag == EDIT_FLAG_UPDATE

			jTextField1.setText(args[2]);
			jTextField2.setText(args[3]);
			jTextField3.setText(args[4]);
			jTextField4.setText(args[5]);
			jTextField5.setText(args[6]);

			// Network Plan Name.
			jTextField6.setText(args[0]);

			jComboBox1.setSelectedItem(args[1]);

			if (args[7].equals(GlobalVar.SET_IP_VALUE_AUTO)) {

				isIpAuto = GlobalVar.SET_IP_VALUE_AUTO;
				jRadioButton1.setSelected(true);

				jTextField1.setEditable(false);
				jTextField2.setEditable(false);
				jTextField3.setEditable(false);
			} else {

				isIpAuto = GlobalVar.SET_IP_VALUE_MANUAL;
				jRadioButton1.setSelected(false);
			}

			if (args[8].equals(GlobalVar.SET_DNS_VALUE_AUTO)) {

				isDnsAuto = GlobalVar.SET_DNS_VALUE_AUTO;
				jRadioButton2.setSelected(true);

				jTextField4.setEditable(false);
				jTextField5.setEditable(false);
			} else {

				isDnsAuto = GlobalVar.SET_DNS_VALUE_MANUAL;
				jRadioButton2.setSelected(false);
			}
		}
	}

	public void refreshJComboBox() {

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(process
				.getSysAdapterNames()));
	}

	// //////////////////////////////////////////////////////////////////////////////
	// Setters & Getters

	public int getEditFlag() {
		return editFlag;
	}

	public void setEditFlag(int editFlag) {
		this.editFlag = editFlag;
	}
}
